name: Test SSH Connection

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-ssh-conn:
    name: Forbidden Pattern Scan
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5

        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            echo "SSH login successful"
            whoami
            exit 0